{application,kvs,
             [{description,"HTTP REST key value storage"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{kvs_app,[]}},
              {applications,[kernel,stdlib,cowboy]},
              {env,[]},
              {modules,[kvs_app,kvs_sup,kvs_db_gen]},
              {maintainers,[]},
              {licenses,[]},
              {links,[]}]}.
