{application,kvs,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{kvs_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[kvs_app,kvs_sup,kvs_db_gen,kvs_http_gen]},
              {maintainers,[]},
              {licenses,[]},
              {links,[]}]}.
